version: "3.9"

services:
  postgres:
    container_name: postgres_container
    image: postgres:alpine
    ports:
      - "5433:5432"
    env_file:
      - .env
    volumes:
      - "postgres:/var/lib/postgresql/data"

volumes:
  postgres:
