version: "3.9"

services:
  postgres:
    container_name: postgres_container_test
    image: postgres:alpine
    ports:
      # - "5443:5432"
      - "${DB_PORT}:5432"
    env_file:
      - test.env
    volumes:
      - "postgres-test:/var/lib/postgresql/data"

volumes:
  postgres-test:
